[package]
name = "wifistop"
version = "0.1.0"
edition = "2018"
build = "build.rs"
license = "MIT"

[dependencies]
pnet = "0.28.0"
os_info = "3.0"
cached = "0.24.0"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "^0.1"